name: super_base_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.4
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  responsive_sizer: ^3.3.1
  shimmer: ^3.0.0
  flutter_slidable: ^3.1.2
  provider: ^6.1.5
  timeago: ^3.7.1
  image_picker: ^1.1.2
  file_picker: ^8.1.6
  url_launcher: ^6.3.1
  mime: ^2.0.0
  flutter_linkify: ^6.0.0
  linkify: ^5.0.0
  rename_app: ^1.6.5
  photo_view: ^0.15.0
  dio: ^5.9.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  gal: ^2.3.2
  share_plus: ^12.0.2
  syncfusion_flutter_pdfviewer: ^33.2.5
  open_filex: ^4.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    # - assets/images/
